### ISSUE TITLE
Upload jar to maven central

### ISSUE THREAD

**Issue by ruben-burr** [NovaTecConsulting/stereotype-check#10]

**Comment by volkerkochnovatec** [comment]
https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by volkerkochnovatec** [comment]
https://jira.novatec-gmbh.de/browse/TS-9932

**Comment by volkerkochnovatec** [comment]
Dann Jira-Account anlegen
Dann alle Bestandteile tun die hier den GPG-Key und den JIRA-Account benötigen
http://www.yegor256.com/2014/08/19/how-to-release-to-maven-central.html

**Comment by volkerkochnovatec** [comment]
https://issues.sonatype.org/browse/OSSRH-26507
