### ISSUE TITLE
Build a release in GitHub

### ISSUE THREAD

**Issue by ruben-burr** [NovaTecConsulting/stereotype-check#24]
Build releases with tags and versions on GitHub

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is '2.0'

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is `2.0`

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is `2.0`

**Comment by simon-weimann** [comment]
@rultor release, tag is `2.0`

**Comment by simon-weimann** [comment]
@rultor release, tag is `2.0.0`

**Comment by simon-weimann** [comment]
@rultor release, tag is `2.0.0`

**Comment by simon-weimann** [comment]
ich denke das funktioniert so nicht :(

rultor versucht mit dem versionsplugin eine konkrete version in den poms zu setzten. wenn diese aber bereits schon so in den poms definiert ist (2.0.0), dann bricht der build ab (nothing to commit)

wenn wir eine andere version definieren als, die in den poms, dann bricht der build ebenfalls, da tycho eine abgleich der version in der pom und im manifest.mf macht. die manifest.mf wird nicht von rultor modifiziert.

momentan also deadlock :(

**Comment by volkerkochnovatec** [comment]
Es ist ja ganz häufig so daß in den poms zur Entwicklungszeit als version 2.0.0-SNAPSHOT drinsteht und sobald das release gebaut wird, wird überall über das versions-plugin 2.0.0 eingetragen. Würde das den Deadlock lösen?

**Comment by simon-weimann** [comment]
Nur wenn wir es schaffen, dass das versionsplugin auch die manifest.mf datei mit anpasst

**Comment by simon-weimann** [comment]
@rultor release, tag is `2.0.0`

**Comment by simon-weimann** [comment]
@rultor release, tag is `2.0.0`

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is `2.0.0`

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is `2.0.0`

**Comment by volkerkochnovatec** [comment]
@rultor release, tag is `2.0.0`

**Comment by ruben-burr** [comment]
@rultor release tag is ´2.0.1´

**Comment by ruben-burr** [comment]
@rultor release tag is `2.0.1`
