### ISSUE TITLE
Define a target plattform for eclipse build

### ISSUE THREAD

**Issue by simon-weimann** [NovaTecConsulting/stereotype-check#32]
See:

http://www.vogella.com/tutorials/EclipseTargetPlatform/article.html

http://stackoverflow.com/questions/34070447/need-apache-commons-lang3-as-dependency-of-an-eclipse-plugin-built-with-tycho

http://codeandme.blogspot.de/2012/12/tycho-build-8-using-target-platform.html

**Comment by volkerkochnovatec** [comment]
@rultor release tag is `2.0.2`
