### ISSUE TITLE
Create update site for eclipse plugin

### ISSUE THREAD

**Issue by ruben-burr** [NovaTecConsulting/stereotype-check#9]
Perhaps this can be done on github directly

**Comment by volkerkochnovatec** [comment]
Für LivingDoc gibts eine Update-Site bei Novatec:

http://www.novatec-gmbh.de/updatesite/testit/livingdoc/livingdoc-eclipse4/releases/1.1.2/

**Comment by volkerkochnovatec** [comment]
TS-9961 - Eclipse-Update-Site für Stereotype-Checker auf FTP-Server

**Comment by volkerkochnovatec** [comment]
todo settings.xml neu mit rultor verschlüsseln
